# Generated by Django 5.2.17 on 2026-09-22 17:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pict', '0033_alter_contactrequest_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название в admin')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок квиза')),
                ('is_enabled', models.BooleanField(db_index=True, default=False, verbose_name='Включён')),
                ('trigger_key', models.CharField(help_text='Ссылка для открытия будет иметь вид #popup:ключ.', max_length=80, unique=True, validators=[django.core.validators.RegexValidator(message='Используйте строчные латинские буквы, цифры, дефис и подчёркивание.', regex='^[a-z0-9_-]+$')], verbose_name='Ключ ссылки')),
                ('page_paths', models.TextField(blank=True, help_text='Пусто — все публичные страницы. Или точные локальные пути, по одному на строку, например /about/ и /skinali/.', verbose_name='Страницы')),
                ('show_launcher', models.BooleanField(default=True, verbose_name='Показывать кнопку запуска')),
                ('launcher_text', models.CharField(default='Пройти тест', max_length=80, verbose_name='Текст кнопки запуска')),
                ('launcher_position', models.CharField(choices=[('left', 'Слева'), ('right', 'Справа')], default='left', max_length=10, verbose_name='Сторона кнопки запуска')),
                ('auto_open_enabled', models.BooleanField(default=True, verbose_name='Включить автопоказ')),
                ('auto_open_delay_seconds', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3600)], verbose_name='Задержка автопоказа, секунд')),
                ('repeat_after_days', models.PositiveSmallIntegerField(default=3, help_text='0 — разрешать автопоказ при каждой новой загрузке страницы.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3650)], verbose_name='Повторный автопоказ через, дней')),
                ('auto_open_on_mobile', models.BooleanField(default=True, verbose_name='Автопоказ на мобильных')),
                ('disable_auto_open_after_submit', models.BooleanField(default=True, verbose_name='Не показывать автоматически после заявки')),
                ('restart_on_close', models.BooleanField(default=True, verbose_name='Начинать заново после закрытия')),
                ('final_title', models.CharField(max_length=200, verbose_name='Заголовок формы')),
                ('final_text', models.TextField(verbose_name='Текст перед формой')),
                ('submit_button_text', models.CharField(max_length=160, verbose_name='Текст кнопки отправки')),
                ('success_title', models.CharField(max_length=160, verbose_name='Заголовок после отправки')),
                ('success_text', models.TextField(verbose_name='Сообщение после отправки')),
                ('success_extra', models.TextField(blank=True, verbose_name='Дополнительный текст после отправки')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменён')),
            ],
            options={
                'verbose_name': 'Квиз',
                'verbose_name_plural': 'Квиз',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Вопрос')),
                ('description', models.TextField(blank=True, verbose_name='Пояснение')),
                ('kind', models.CharField(choices=[('image', 'Один вариант с изображениями'), ('choice', 'Один вариант списком'), ('text', 'Текстовый ответ')], max_length=20, verbose_name='Тип вопроса')),
                ('placeholder', models.CharField(blank=True, max_length=160, verbose_name='Подсказка в поле')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Показывать')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Вопрос квиза',
                'verbose_name_plural': 'Вопросы квиза',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Вариант ответа')),
                ('bundled_image', models.CharField(blank=True, choices=[('', 'Без исходного изображения'), ('quiz/images/answers/layout-straight.jpg', 'Планировка: прямая'), ('quiz/images/answers/layout-corner.jpg', 'Планировка: угловая'), ('quiz/images/answers/layout-u-shaped.jpg', 'Планировка: П-образная'), ('quiz/images/answers/layout-island.jpg', 'Планировка: кухня с островом'), ('quiz/images/answers/layout-two-row.jpg', 'Планировка: двухрядная'), ('quiz/images/answers/layout-other.jpg', 'Планировка: другая'), ('quiz/images/answers/skinali-photo-print.jpg', 'Вид: с фотопечатью'), ('quiz/images/answers/skinali-solid.jpg', 'Вид: однотонное'), ('quiz/images/answers/skinali-transparent.jpg', 'Вид: прозрачное'), ('quiz/images/answers/gift-clock.jpg', 'Подарок: часы'), ('quiz/images/answers/gift-hood-glass.jpg', 'Подарок: стекло под вытяжкой'), ('quiz/images/answers/gift-discount.jpg', 'Подарок: скидка'), ('quiz/images/answers/gift-shelves.jpg', 'Подарок: полки')], help_text='Загруженное изображение имеет приоритет над исходным.', max_length=200, verbose_name='Исходное изображение')),
                ('image', models.ImageField(blank=True, upload_to='quiz/options/', verbose_name='Загруженное изображение')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Показывать')),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='quiz.quizquestion', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответов',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.JSONField(default=list, verbose_name='Снимок ответов')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('contact_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_submission', to='pict.contactrequest', verbose_name='Заявка')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='quiz.quiz', verbose_name='Квиз')),
            ],
            options={
                'verbose_name': 'Ответ на квиз',
                'verbose_name_plural': 'Ответы на квиз',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
