# Generated by Django 5.2.17 on 2026-09-08 15:40

import django.db.models.deletion
from django.db import migrations, models


def create_main_menu(apps, schema_editor):
    """Переносит исходное меню из Python-списка в управляемые записи."""
    site_menu_model = apps.get_model('sitecontent', 'SiteMenu')
    menu_item_model = apps.get_model('sitecontent', 'MenuItem')
    menu = site_menu_model.objects.create(name='Основное меню', code='main')
    menu_item_model.objects.bulk_create([
        menu_item_model(menu=menu, title='Главная страница', url='/', position=10),
        menu_item_model(menu=menu, title='Каталог скинали', url='/skinali/', position=20),
        menu_item_model(
            menu=menu,
            title='Наши работы',
            url='/foto-skinali-iz-stekla/',
            position=30,
        ),
        menu_item_model(menu=menu, title='Услуги дизайнера', url='/designer', position=40),
        menu_item_model(menu=menu, title='Связаться с нами', url='/about/', position=50),
    ])


def remove_main_menu(apps, schema_editor):
    site_menu_model = apps.get_model('sitecontent', 'SiteMenu')
    site_menu_model.objects.filter(code='main').delete()


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SiteMenu',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        default='Основное меню',
                        editable=False,
                        max_length=100,
                        verbose_name='Название',
                    ),
                ),
                (
                    'code',
                    models.SlugField(
                        default='main',
                        editable=False,
                        unique=True,
                        verbose_name='Системный код',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                (
                    'url',
                    models.CharField(
                        help_text=(
                            'Допустимы внутренние пути с /, якоря #, http/https, tel: и mailto:. '
                            'Например: /about/, https://example.com, #contacts или tel:+375291234567.'
                        ),
                        max_length=500,
                        verbose_name='Ссылка',
                    ),
                ),
                (
                    'open_in_new_tab',
                    models.BooleanField(default=False, verbose_name='Открывать в новой вкладке'),
                ),
                ('position', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Отображать')),
                (
                    'menu',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='items',
                        to='sitecontent.sitemenu',
                        verbose_name='Меню',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Пункты меню',
                'ordering': ['position', 'pk'],
            },
        ),
        migrations.RunPython(create_main_menu, remove_main_menu),
    ]
