# Generated by Django 5.2.17 on 2026-09-30 12:05

import django.core.validators
from django.db import migrations, models


def seed_telegram_connection(apps, schema_editor):
    apps.get_model('sitecontent', 'LeadConnection').objects.using(schema_editor.connection.alias).create(
        name='Telegram (настройки сервера)', provider='telegram', is_enabled=True, use_environment=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0003_sitepage_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], max_length=20, verbose_name='Сервис')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Включено')),
                ('all_request_types', models.BooleanField(default=True, verbose_name='Все типы заявок')),
                ('request_types', models.JSONField(blank=True, default=list, verbose_name='Типы заявок')),
                ('recipients', models.JSONField(blank=True, default=list, verbose_name='Получатели')),
                ('use_environment', models.BooleanField(default=False, verbose_name='Использовать настройки Telegram из окружения')),
                ('telegram_token_encrypted', models.TextField(blank=True, editable=False)),
                ('proxy_url_encrypted', models.TextField(blank=True, editable=False)),
                ('smtp_host', models.CharField(blank=True, max_length=253, verbose_name='SMTP-сервер')),
                ('smtp_port', models.PositiveIntegerField(default=587, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='Порт')),
                ('smtp_security', models.CharField(choices=[('starttls', 'STARTTLS'), ('ssl', 'SSL/TLS')], default='starttls', max_length=20, verbose_name='Защита соединения')),
                ('smtp_username', models.CharField(blank=True, max_length=254, verbose_name='Логин SMTP')),
                ('smtp_password_encrypted', models.TextField(blank=True, editable=False)),
                ('from_email', models.EmailField(blank=True, max_length=254, verbose_name='Адрес отправителя')),
                ('from_name', models.CharField(blank=True, max_length=100, verbose_name='Имя отправителя')),
                ('connect_timeout', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Тайм-аут соединения, сек.')),
                ('read_timeout', models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Тайм-аут ответа, сек.')),
                ('configuration_error', models.TextField(blank=True, editable=False, verbose_name='Ошибка настройки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменено')),
            ],
            options={
                'verbose_name': 'Подключение',
                'verbose_name_plural': 'Обработка заявок',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.RunPython(seed_telegram_connection, migrations.RunPython.noop),
    ]
