# Generated by Django 5.2.17 on 2026-10-05 15:52

from django.db import migrations, models


def add_article_section(apps, schema_editor):
    alias = schema_editor.connection.alias
    Page = apps.get_model('sitecontent', 'SitePage')
    Page.objects.using(alias).get_or_create(code='article_list')
    Menu = apps.get_model('sitecontent', 'SiteMenu')
    Item = apps.get_model('sitecontent', 'MenuItem')
    menu = Menu.objects.using(alias).filter(code='main').first()
    if menu is None or Item.objects.using(alias).filter(menu=menu, url='/polezno-znat/').exists():
        return
    items = list(Item.objects.using(alias).filter(menu=menu).order_by('position', 'pk'))
    designer = next((index for index, item in enumerate(items) if item.url == '/designer/'), None)
    contact = next((index for index, item in enumerate(items) if item.url == '/about/'), len(items))
    insertion = designer + 1 if designer is not None else contact
    before = items[insertion - 1].position if insertion else 0
    after = items[insertion].position if insertion < len(items) else before + 20
    if after - before < 2:
        for index, item in enumerate(items):
            item.position = (index + 1 + (index >= insertion)) * 10
            item.save(using=alias, update_fields=['position'])
        position = (insertion + 1) * 10
    else:
        position = (before + after) // 2
    Item.objects.using(alias).create(menu=menu, title='Полезно знать', url='/polezno-znat/', position=position)


def remove_article_section(apps, schema_editor):
    alias = schema_editor.connection.alias
    apps.get_model('sitecontent', 'SitePage').objects.using(alias).filter(code='article_list').delete()
    apps.get_model('sitecontent', 'MenuItem').objects.using(alias).filter(
        menu__code='main', url='/polezno-znat/', title='Полезно знать',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sitecontent', '0005_designer_trailing_slash'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='articles/content/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Загружено')),
            ],
            options={
                'verbose_name': 'Изображение статьи',
                'verbose_name_plural': 'Изображения статей',
            },
        ),
        migrations.AlterField(
            model_name='sitepage',
            name='code',
            field=models.CharField(choices=[('home', 'Главная страница'), ('skinali', 'Каталог скинали'), ('finished_works', 'Наши работы'), ('designer', 'Услуги дизайнера'), ('article_list', 'Полезно знать'), ('about', 'Связаться с нами')], editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='Системный код'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seo_title', models.CharField(blank=True, help_text='Без «| ОДИУМ»: бренд и номер страницы добавятся автоматически.', max_length=200, verbose_name='SEO-title')),
                ('seo_description', models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартное описание.', max_length=320, verbose_name='Meta description')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения публичного содержимого')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(editable=False, max_length=220, unique=True, verbose_name='Адрес статьи')),
                ('summary', models.TextField(max_length=600, verbose_name='Краткое описание')),
                ('cover', models.ImageField(max_length=255, upload_to='articles/covers/', verbose_name='Обложка')),
                ('body', models.TextField(verbose_name='Текст статьи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('published_at', models.DateTimeField(blank=True, help_text='Заполнится при первой публикации. Можно изменить вручную для порядка статей.', null=True, verbose_name='Дата первой публикации')),
                ('images', models.ManyToManyField(blank=True, editable=False, related_name='articles', to='sitecontent.articleimage')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ('-published_at', '-pk'),
                'indexes': [models.Index(fields=['is_published', '-published_at', '-id'], name='article_publication_order')],
            },
        ),
        migrations.RunPython(add_article_section, remove_article_section),
    ]
