"""
Django settings for skinali project.

Generated by 'django-admin startproject' using Django 4.1.5 and updated for Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import re
from pathlib import Path
from urllib.parse import urlsplit

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR.parent / '.env'


def load_environment_file(path):
    """Загружает простой KEY=VALUE-файл, не заменяя системное окружение."""
    if not path.exists():
        return

    for line_number, raw_line in enumerate(
        path.read_text(encoding='utf-8-sig').splitlines(),
        start=1,
    ):
        line = raw_line.strip()
        if not line or line.startswith('#'):
            continue
        key, separator, value = line.partition('=')
        key = key.strip()
        if not separator or not key.isidentifier():
            raise RuntimeError(
                f'Некорректная строка {line_number} в файле окружения.'
            )
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        os.environ.setdefault(key, value)


load_environment_file(ENV_FILE)


TRUE_ENV_VALUES = {'1', 'true', 'yes', 'on'}
FALSE_ENV_VALUES = {'0', 'false', 'no', 'off'}


def get_environment_bool(name, default):
    """Читает логический параметр окружения без неявных преобразований строк."""
    raw_value = os.environ.get(name, '').strip().lower()
    if not raw_value:
        return default
    if raw_value in TRUE_ENV_VALUES:
        return True
    if raw_value in FALSE_ENV_VALUES:
        return False
    raise ImproperlyConfigured(
        f'{name} должен содержать true/false, 1/0, yes/no или on/off.'
    )


def get_environment_list(name, default=()):
    """Разбирает список значений окружения, разделённых запятыми."""
    raw_value = os.environ.get(name, '').strip()
    if not raw_value:
        return list(default)
    return [item.strip() for item in raw_value.split(',') if item.strip()]


def get_environment_int(name, default, *, minimum=0):
    """Читает целое число и проверяет его нижнюю границу."""
    raw_value = os.environ.get(name, '').strip()
    if not raw_value:
        return default
    try:
        value = int(raw_value)
    except ValueError as error:
        raise ImproperlyConfigured(f'{name} должен быть целым числом.') from error
    if value < minimum:
        raise ImproperlyConfigured(f'{name} должен быть не меньше {minimum}.')
    return value


def get_environment_url_prefix(name, default):
    """Нормализует безопасный URL-префикс без начального слеша."""
    value = os.environ.get(name, default).strip().strip('/')
    if not value or not re.fullmatch(r'[A-Za-z0-9_-]+(?:/[A-Za-z0-9_-]+)*', value):
        raise ImproperlyConfigured(
            f'{name} должен состоять из латинских букв, цифр, дефисов и слешей.'
        )
    return f'{value}/'


def get_environment_origin(name, default):
    """Проверяет публичный origin без пути, параметров и учётных данных."""
    value = os.environ.get(name, default).strip().rstrip('/')
    parsed = urlsplit(value)
    if (
        parsed.scheme not in {'http', 'https'}
        or not parsed.netloc
        or parsed.path
        or parsed.query
        or parsed.fragment
        or parsed.username
        or parsed.password
    ):
        raise ImproperlyConfigured(
            f'{name} должен иметь вид https://example.com без пути и параметров.'
        )
    return value


ENVIRONMENT = os.environ.get('DJANGO_ENVIRONMENT', 'development').strip().lower()
if ENVIRONMENT not in {'development', 'production'}:
    raise ImproperlyConfigured(
        'DJANGO_ENVIRONMENT должен быть development или production.'
    )
IS_PRODUCTION = ENVIRONMENT == 'production'


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# Этот ключ предназначен только для локальной разработки и никогда не используется в production.
DEVELOPMENT_SECRET_KEY = 'django-insecure-)c)veha1$umvb5__q!oq8eei!03my0xn(gw+vhgnwt2k%pq-@3'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', '').strip()
if IS_PRODUCTION and not SECRET_KEY:
    raise ImproperlyConfigured('В production необходимо задать DJANGO_SECRET_KEY.')
if IS_PRODUCTION and SECRET_KEY.startswith('django-insecure-'):
    raise ImproperlyConfigured(
        'Production-ключ DJANGO_SECRET_KEY не должен начинаться с django-insecure-.'
    )
if not SECRET_KEY:
    SECRET_KEY = DEVELOPMENT_SECRET_KEY

# Production-профиль запрещает DEBUG даже при ошибочно заданной переменной окружения.
DEBUG = get_environment_bool('DJANGO_DEBUG', not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG нельзя включать в production.')

ALLOWED_HOSTS = get_environment_list(
    'DJANGO_ALLOWED_HOSTS',
    default=('127.0.0.1', 'localhost') if not IS_PRODUCTION else (),
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('В production необходимо задать DJANGO_ALLOWED_HOSTS.')
if IS_PRODUCTION and '*' in ALLOWED_HOSTS:
    raise ImproperlyConfigured('Значение * запрещено в production DJANGO_ALLOWED_HOSTS.')

INTERNAL_IPS = get_environment_list(
    'DJANGO_INTERNAL_IPS',
    default=('127.0.0.1',) if not IS_PRODUCTION else (),
)
ADMIN_URL = get_environment_url_prefix('DJANGO_ADMIN_PATH', 'admin')
PUBLIC_SITE_ORIGIN = get_environment_origin(
    'DJANGO_PUBLIC_SITE_ORIGIN',
    'https://odium.by',
)
if IS_PRODUCTION and not PUBLIC_SITE_ORIGIN.startswith('https://'):
    raise ImproperlyConfigured(
        'DJANGO_PUBLIC_SITE_ORIGIN должен использовать HTTPS в production.'
    )
ENABLE_DJANGO_EXTENSIONS = get_environment_bool(
    'DJANGO_ENABLE_DJANGO_EXTENSIONS',
    not IS_PRODUCTION,
)
ENABLE_DEBUG_TOOLBAR = get_environment_bool(
    'DJANGO_ENABLE_DEBUG_TOOLBAR',
    DEBUG and not IS_PRODUCTION,
)
if IS_PRODUCTION and ENABLE_DEBUG_TOOLBAR:
    raise ImproperlyConfigured('Debug Toolbar нельзя включать в production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'pict.apps.PictConfig',
    'sitecontent.apps.SiteContentConfig',
    'sorl.thumbnail',
]

if ENABLE_DJANGO_EXTENSIONS:
    INSTALLED_APPS.append('django_extensions')
if ENABLE_DEBUG_TOOLBAR:
    INSTALLED_APPS.append('debug_toolbar')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if ENABLE_DEBUG_TOOLBAR:
    MIDDLEWARE.append('debug_toolbar.middleware.DebugToolbarMiddleware')

ROOT_URLCONF = 'skinali.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'pict.context_processors.contact_forms',
                'sitecontent.context_processors.site_navigation',
            ],
        },
    },
]

WSGI_APPLICATION = 'skinali.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Store session data in a signed browser cookie instead of writing it to SQLite.
SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# HTTPS-защита включается автоматически только в production-профиле.
SESSION_COOKIE_SECURE = IS_PRODUCTION
CSRF_COOKIE_SECURE = IS_PRODUCTION
SECURE_SSL_REDIRECT = get_environment_bool(
    'DJANGO_SECURE_SSL_REDIRECT',
    IS_PRODUCTION,
)
SECURE_HSTS_SECONDS = get_environment_int('DJANGO_SECURE_HSTS_SECONDS', 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = get_environment_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS',
    False,
)
SECURE_HSTS_PRELOAD = get_environment_bool(
    'DJANGO_SECURE_HSTS_PRELOAD',
    False,
)
CSRF_TRUSTED_ORIGINS = get_environment_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Доверять X-Forwarded-Proto можно только когда заголовок задаёт контролируемый reverse proxy.
if get_environment_bool('DJANGO_TRUST_X_FORWARDED_PROTO', False):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = []

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Превью каталога создаются один раз и повторно используются из media/cache/thumbnails/.
THUMBNAIL_PREFIX = 'cache/thumbnails/'
THUMBNAIL_QUALITY = 82
THUMBNAIL_PROGRESSIVE = True
THUMBNAIL_UPSCALE = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Секреты Telegram передаются окружением и никогда не хранятся в репозитории.
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN', '').strip()
TELEGRAM_CHAT_ID = os.environ.get('TELEGRAM_CHAT_ID', '').strip()
TELEGRAM_PROXY_URL = os.environ.get('TELEGRAM_PROXY_URL', '').strip()
TELEGRAM_CONNECT_TIMEOUT = float(os.environ.get('TELEGRAM_CONNECT_TIMEOUT', '3'))
TELEGRAM_READ_TIMEOUT = float(os.environ.get('TELEGRAM_READ_TIMEOUT', '5'))
