# Generated by Django 4.1.5 on 2023-03-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='pict',
            options={'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='photo',
            field=models.ImageField(upload_to='photos/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='time_update',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время добавления'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Ключ'),
        ),
    ]
