# Generated by Django 4.1.5 on 2023-03-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0002_alter_category_options_alter_pict_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pict',
            options={'ordering': ['id'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='sfs', max_length=100, verbose_name='SlugURL'),
        ),
    ]
