# Generated by Django 4.1.5 on 2023-03-14 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0004_alter_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=100, verbose_name='Цвет')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='SlugURL')),
            ],
            options={
                'verbose_name': 'Цвет',
                'verbose_name_plural': 'Цвета',
            },
        ),
    ]
