# Generated by Django 4.1.5 on 2023-03-14 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0006_pict_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='slug',
            new_name='slug_color',
        ),
    ]
