# Generated by Django 4.1.5 on 2023-03-22 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0007_rename_slug_color_slug_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='pict',
            name='alt',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pict.color', verbose_name='Цвет'),
        ),
    ]
