# Generated by Django 4.1.5 on 2023-10-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0009_alter_pict_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100, verbose_name='Ключевое слово')),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pict',
            name='tags',
            field=models.ManyToManyField(blank=True, to='pict.tagpict'),
        ),
    ]
