# Generated by Django 4.1.5 on 2023-10-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0010_tagpict_pict_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagpict',
            options={'verbose_name': 'Ключевое слово', 'verbose_name_plural': 'Ключевые слова'},
        ),
        migrations.AlterField(
            model_name='tagpict',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
