# Generated by Django 4.1.5 on 2023-10-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0011_alter_tagpict_options_alter_tagpict_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='Описание'),
        ),
    ]
