# Generated by Django 4.1.5 on 2023-10-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0012_alter_pict_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.CharField(db_index=True, max_length=10, unique=True, verbose_name='Имя файла'),
        ),
    ]
