# Generated by Django 4.1.5 on 2023-10-02 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0013_alter_pict_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pict',
            name='title',
        ),
    ]
