# Generated by Django 4.1.5 on 2023-10-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0014_remove_pict_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pict',
            options={'ordering': ['-id'], 'verbose_name': 'Изображения', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterField(
            model_name='pict',
            name='alt',
            field=models.CharField(blank=True, max_length=250, verbose_name='Описание'),
        ),
    ]
