# Generated by Django 4.1.5 on 2023-10-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0015_alter_pict_options_alter_pict_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='pict.tagpict'),
        ),
    ]
