# Generated by Django 4.1.5 on 2023-10-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0016_alter_pict_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='color',
            name='slug_color',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='cat',
            field=models.ManyToManyField(to='pict.category', verbose_name='Категории'),
        ),
        migrations.RemoveField(
            model_name='pict',
            name='color',
        ),
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.IntegerField(db_index=True, unique=True, verbose_name='Имя файла'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='pict.tagpict', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tagpict',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='pict',
            name='color',
            field=models.ManyToManyField(to='pict.color', verbose_name='Цвет'),
        ),
    ]
