# Generated by Django 4.1.5 on 2026-09-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0018_finishedwork'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('callback', 'Обратный звонок'), ('question', 'Вопрос')], max_length=20, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('question', models.CharField(blank=True, max_length=250, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
