# Generated by Django 4.1.5 on 2026-09-02 10:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0019_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequestDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('email', 'Email')], max_length=20, verbose_name='Канал')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('processing', 'Отправляется'), ('retry', 'Ожидает повтора'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попытки')),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, default=django.utils.timezone.now, null=True, verbose_name='Следующая попытка')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Время отправки')),
                ('external_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='ID внешнего сообщения')),
                ('last_error', models.TextField(blank=True, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('contact_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pict.contactrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Доставка заявки',
                'verbose_name_plural': 'Доставки заявок',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='contactrequestdelivery',
            index=models.Index(fields=['channel', 'status', 'next_attempt_at'], name='pict_delivery_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='contactrequestdelivery',
            constraint=models.UniqueConstraint(fields=('contact_request', 'channel'), name='unique_contact_request_delivery_channel'),
        ),
    ]
