# Generated by Django 4.1.5 on 2026-09-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0020_contactrequestdelivery_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='request_type',
            field=models.CharField(
                choices=[
                    ('callback', 'Обратный звонок'),
                    ('question', 'Вопрос'),
                    ('email_message', 'Сообщение по email'),
                ],
                max_length=20,
                verbose_name='Тип заявки',
            ),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(
                blank=True,
                max_length=20,
                verbose_name='Телефон',
            ),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(
                blank=True,
                default='',
                max_length=254,
                verbose_name='Email',
            ),
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='comment',
            field=models.CharField(
                blank=True,
                default='',
                max_length=250,
                verbose_name='Комментарий',
            ),
        ),
    ]
