# Generated by Django 5.2.17 on 2026-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0026_tag_search_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Отображается под заголовком страницы.', verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартное описание.', max_length=320, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартный заголовок.', max_length=200, verbose_name='SEO-заголовок H1'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Без «| ОДИУМ»: бренд и номер страницы добавятся автоматически.', max_length=200, verbose_name='SEO-title'),
        ),
        migrations.AddField(
            model_name='tagpict',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Отображается под заголовком страницы.', verbose_name='Вводный текст'),
        ),
        migrations.AddField(
            model_name='tagpict',
            name='seo_description',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартное описание.', max_length=320, verbose_name='Meta description'),
        ),
        migrations.AddField(
            model_name='tagpict',
            name='seo_h1',
            field=models.CharField(blank=True, help_text='Оставьте пустым, чтобы использовать стандартный заголовок.', max_length=200, verbose_name='SEO-заголовок H1'),
        ),
        migrations.AddField(
            model_name='tagpict',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Без «| ОДИУМ»: бренд и номер страницы добавятся автоматически.', max_length=200, verbose_name='SEO-title'),
        ),
    ]
