# Generated by Django 5.2.17 on 2026-09-17 09:38

import pict.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0028_public_content_timestamps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='alt',
            field=models.CharField(max_length=250, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='pict',
            name='photo',
            field=models.ImageField(
                max_length=255,
                upload_to=pict.models.pict_photo_upload_to,
                verbose_name='Изображение',
            ),
        ),
    ]
