# Generated by Django 5.2.17 on 2026-09-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0029_alter_pict_alt_alter_pict_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pict',
            name='name',
            field=models.IntegerField(
                db_index=True,
                unique=True,
                verbose_name='Номер изображения',
            ),
        ),
    ]
