# Generated by Django 5.2.17 on 2026-09-17 10:24

import re
import unicodedata

from django.db import migrations, models


CYRILLIC_TRANSLITERATION = str.maketrans({
    'а': 'a', 'б': 'b', 'в': 'v', 'г': 'g', 'д': 'd', 'е': 'e',
    'ё': 'yo', 'ж': 'zh', 'з': 'z', 'и': 'i', 'й': 'y', 'к': 'k',
    'л': 'l', 'м': 'm', 'н': 'n', 'о': 'o', 'п': 'p', 'р': 'r',
    'с': 's', 'т': 't', 'у': 'u', 'ф': 'f', 'х': 'kh', 'ц': 'ts',
    'ч': 'ch', 'ш': 'sh', 'щ': 'shch', 'ъ': '', 'ы': 'y', 'ь': '',
    'э': 'e', 'ю': 'yu', 'я': 'ya', 'і': 'i', 'ї': 'yi', 'є': 'ye',
    'ґ': 'g', 'ў': 'u',
})
SLUG_MAX_LENGTH = 220


def transliterate(value):
    normalized = unicodedata.normalize('NFKC', value or '').casefold()
    transliterated = normalized.translate(CYRILLIC_TRANSLITERATION)
    ascii_value = (
        unicodedata.normalize('NFKD', transliterated)
        .encode('ascii', 'ignore')
        .decode('ascii')
    )
    return '-'.join(re.findall(r'[a-z0-9]+', ascii_value))


def build_slug(description, image_number):
    description_slug = transliterate(description) or 'izobrazhenie'
    number_slug = str(image_number)
    number_suffix = f'-{number_slug}'

    if description_slug == number_slug:
        description_slug = 'izobrazhenie'
    elif description_slug.endswith(number_suffix):
        description_slug = description_slug[:-len(number_suffix)]

    description_slug = description_slug[
        :max(1, SLUG_MAX_LENGTH - len(number_suffix))
    ].rstrip('-')
    return f'{description_slug or "izobrazhenie"}{number_suffix}'


def populate_picture_slugs(apps, schema_editor):
    picture_model = apps.get_model('pict', 'Pict')
    for picture in picture_model.objects.only('pk', 'name', 'alt').iterator(
        chunk_size=500,
    ):
        picture_model.objects.filter(pk=picture.pk).update(
            slug=build_slug(picture.alt, picture.name),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0030_alter_pict_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pict',
            name='page_description',
            field=models.TextField(
                blank=True,
                help_text=(
                    'Оставьте пустым, чтобы сформировать описание из названия '
                    'и номера.'
                ),
                verbose_name='Описание страницы',
            ),
        ),
        migrations.AddField(
            model_name='pict',
            name='seo_description',
            field=models.CharField(
                blank=True,
                help_text='Оставьте пустым, чтобы использовать стандартное описание.',
                max_length=320,
                verbose_name='Meta description',
            ),
        ),
        migrations.AddField(
            model_name='pict',
            name='seo_h1',
            field=models.CharField(
                blank=True,
                help_text='Оставьте пустым, чтобы использовать стандартный заголовок.',
                max_length=200,
                verbose_name='SEO-заголовок H1',
            ),
        ),
        migrations.AddField(
            model_name='pict',
            name='seo_title',
            field=models.CharField(
                blank=True,
                help_text=(
                    'Без «| ОДИУМ»: бренд и номер страницы добавятся автоматически.'
                ),
                max_length=200,
                verbose_name='SEO-title',
            ),
        ),
        migrations.AddField(
            model_name='pict',
            name='slug',
            field=models.SlugField(
                editable=False,
                max_length=220,
                null=True,
                unique=True,
                verbose_name='Slug страницы',
            ),
        ),
        migrations.RunPython(
            populate_picture_slugs,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='pict',
            name='slug',
            field=models.SlugField(
                editable=False,
                max_length=220,
                unique=True,
                verbose_name='Slug страницы',
            ),
        ),
        migrations.AlterField(
            model_name='pict',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True,
                verbose_name='Время изменения публичного содержимого',
            ),
        ),
    ]
