# Generated by Django 5.2.17 on 2026-09-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0031_pict_detail_page_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='finishedwork',
            name='glass_type',
            field=models.CharField(choices=[('standard', 'Обычное'), ('optiwhite', 'Optiwhite'), ('diamant', 'Diamant')], default='standard', max_length=10, verbose_name='Тип стекла'),
        ),
        migrations.AddField(
            model_name='finishedwork',
            name='paint_color',
            field=models.CharField(blank=True, default='', help_text='Например: RAL 9000.', max_length=50, verbose_name='Цвет покраски'),
        ),
        migrations.AddField(
            model_name='finishedwork',
            name='skinali_type',
            field=models.CharField(choices=[('print', 'Печать'), ('paint', 'Покраска'), ('transparent', 'Прозрачное')], default='print', max_length=11, verbose_name='Тип скинали'),
        ),
        migrations.AddConstraint(
            model_name='finishedwork',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('paint_color', ''), ('skinali_type', 'print')), models.Q(('catalog_image__isnull', True), ('skinali_type', 'paint'), models.Q(('paint_color', ''), _negated=True)), models.Q(('catalog_image__isnull', True), ('paint_color', ''), ('skinali_type', 'transparent')), _connector='OR'), name='finished_work_fields_match_skinali_type'),
        ),
    ]
