# Generated by Django 5.2.17 on 2026-09-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0032_finishedwork_glass_type_finishedwork_paint_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='request_type',
            field=models.CharField(choices=[('callback', 'Обратный звонок'), ('question', 'Вопрос'), ('email_message', 'Сообщение по email'), ('image_purchase', 'Покупка изображения'), ('quiz', 'Квиз')], max_length=20, verbose_name='Тип заявки'),
        ),
    ]
