# Generated by Django 5.2.17 on 2026-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0033_alter_contactrequest_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pict',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярное изображение'),
        ),
    ]
