# Generated by Django 5.2.17 on 2026-09-25 17:36

import pict.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0034_pict_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finishedwork',
            name='photo',
            field=models.ImageField(max_length=255, upload_to=pict.models.finished_work_photo_upload_to, verbose_name='Фото'),
        ),
    ]
