# Generated by Django 5.2.17 on 2026-09-25 18:05

from django.db import migrations, models


def set_initial_category_positions(apps, schema_editor):
    Category = apps.get_model('pict', 'Category')
    categories = list(Category.objects.order_by('pk'))
    for position, category in enumerate(categories, start=1):
        category.position = position
    Category.objects.bulk_update(categories, ['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0035_alter_finishedwork_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position', 'pk'], 'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False, verbose_name='Порядок'),
        ),
        migrations.RunPython(
            set_initial_category_positions,
            migrations.RunPython.noop,
        ),
    ]
