# Generated by Django 5.2.17 on 2026-09-30 12:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


def attach_existing_deliveries(apps, schema_editor):
    alias = schema_editor.connection.alias
    Connection = apps.get_model('sitecontent', 'LeadConnection')
    Delivery = apps.get_model('pict', 'ContactRequestDelivery')
    telegram = Connection.objects.using(alias).get(provider='telegram', use_environment=True)
    connections = {'telegram': telegram.pk}
    for delivery in Delivery.objects.using(alias).all().iterator():
        if delivery.channel not in connections:
            connection = Connection.objects.using(alias).create(
                name='Архив email', provider=delivery.channel, is_enabled=False,
            )
            connections[delivery.channel] = connection.pk
        Delivery.objects.using(alias).filter(pk=delivery.pk).update(
            connection_id=connections[delivery.channel], message_key=uuid.uuid4(),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pict', '0036_alter_category_options_category_position'),
        ('sitecontent', '0004_leadconnection'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contactrequestdelivery',
            name='unique_contact_request_delivery_channel',
        ),
        migrations.RemoveIndex(
            model_name='contactrequestdelivery',
            name='pict_delivery_due_idx',
        ),
        migrations.AddField(
            model_name='contactrequestdelivery',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sitecontent.leadconnection', verbose_name='Подключение'),
        ),
        migrations.AddField(
            model_name='contactrequestdelivery',
            name='message_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='contactrequestdelivery',
            name='recipient',
            field=models.CharField(blank=True, max_length=254, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='contactrequestdelivery',
            name='test_batch_id',
            field=models.UUIDField(blank=True, editable=False, null=True, verbose_name='Группа тестовой отправки'),
        ),
        migrations.AlterField(
            model_name='contactrequestdelivery',
            name='contact_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='pict.contactrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='contactrequestdelivery',
            name='external_message_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='ID внешнего сообщения'),
        ),
        migrations.AddIndex(
            model_name='contactrequestdelivery',
            index=models.Index(fields=['connection', 'status', 'next_attempt_at'], name='pict_connection_due_idx'),
        ),
        migrations.RunPython(attach_existing_deliveries),
        migrations.AlterField(
            model_name='contactrequestdelivery', name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='sitecontent.leadconnection', verbose_name='Подключение'),
        ),
        migrations.AlterField(
            model_name='contactrequestdelivery', name='message_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddConstraint(
            model_name='contactrequestdelivery',
            constraint=models.UniqueConstraint(fields=('contact_request', 'connection', 'recipient'), name='unique_request_connection_target'),
        ),
        migrations.AddConstraint(
            model_name='contactrequestdelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('contact_request__isnull', False), ('test_batch_id__isnull', True)), models.Q(('contact_request__isnull', True), ('test_batch_id__isnull', False)), _connector='OR'), name='delivery_request_or_test'),
        ),
    ]
